/*SELECT RENT_VILLA_ID R1, COUNT(*) BEFORE_COUNT
    FROM WEB_RENT
    WHERE RENT_START_DATE BETWEEN '01-JAN-13' AND '31-AUG-13'
    GROUP BY RENT_VILLA_ID;

SELECT RENT_VILLA_ID R2, COUNT(*) AFTER_COUNT
    FROM WEB_RENT
    WHERE RENT_START_DATE BETWEEN '01-JAN-14' AND '31-AUG-14'
    GROUP BY RENT_VILLA_ID;
*/
CREATE VIEW OWNER AS
SELECT R1
FROM
(SELECT RENT_VILLA_ID R1, COUNT(*) AFTER_COUNT
    FROM WEB_RENT
    WHERE RENT_START_DATE BETWEEN '01-JAN-14' AND '31-AUG-14'
    GROUP BY RENT_VILLA_ID
)LEFT JOIN  
(SELECT RENT_VILLA_ID R2, COUNT(*) BEFORE_COUNT
    FROM WEB_RENT
    WHERE RENT_START_DATE BETWEEN '01-JAN-13' AND '31-AUG-13'
    GROUP BY RENT_VILLA_ID
) ON R1=R2
WHERE ((AFTER_COUNT-BEFORE_COUNT)/BEFORE_COUNT)*100 >10
OR BEFORE_COUNT IS NULL;

SELECT USER_FIRST_NAME, USER_LAST_NAME
FROM WEB_USER,(SELECT DISTINCT VILLA_OWNER_ID
               FROM WEB_VILLA,OWNER
               WHERE R1 = VILLA_ID) VILLA_OWNER
WHERE USER_ID = VILLA_OWNER_ID;
    
DROP VIEW OWNER;