SELECT USER_FIRST_NAME, USER_LAST_NAME, RENT_AMOUNT_USER_DEPOSIT
FROM WEB_USER,
    (SELECT RENT_USER_ID, RENT_AMOUNT_USER_DEPOSIT
      FROM WEB_RENT
      WHERE EXTRACT(YEAR FROM RENT_START_DATE ) = '2013'
      ORDER BY RENT_AMOUNT_USER_DEPOSIT DESC
      )
WHERE USER_ID = RENT_USER_ID
AND ROWNUM <=3
ORDER BY RENT_AMOUNT_USER_DEPOSIT
;