SELECT TRUNC(AVG(MONTHS_BETWEEN(SYSDATE,USER_DOB)/12)) AVERAGE_AGE
FROM WEB_USER,
  (SELECT RENT_USER_ID
    FROM WEB_RENT
    WHERE RENT_START_DATE BETWEEN '01-SEP-13' AND '31-DEC-13'
    )
WHERE RENT_USER_ID = USER_ID;