SELECT VILLA_NAME, USER_FIRST_NAME, USER_LAST_NAME
FROM WEB_VILLA ,WEB_OWNER,WEB_USER,
    (SELECT REVIEW_VILLA_ID, AVG(REVIEW_RATING) RATING 
      FROM WEB_REVIEW
      GROUP BY REVIEW_VILLA_ID
      ORDER BY AVG(REVIEW_RATING)DESC)
WHERE VILLA_ID = REVIEW_VILLA_ID
AND VILLA_OWNER_ID = OWNER_ID
AND OWNER_ID = USER_ID
AND ROWNUM <=3
;