CREATE VIEW VILLA_NIGHT_SUM AS
SELECT RENT_VILLA_ID,SUM(NIGHTS) TOTAL_NIGHTS
        FROM (SELECT RENT_VILLA_ID, (RENT_END_DATE - RENT_START_DATE) NIGHTS
          FROM WEB_RENT WHERE  EXTRACT(YEAR FROM RENT_START_DATE ) = '2014' )
    GROUP BY RENT_VILLA_ID
;

SELECT VILLA_NAME
FROM WEB_VILLA
WHERE VILLA_ID = (SELECT RENT_VILLA_ID
                  FROM VILLA_NIGHT_SUM
                  WHERE TOTAL_NIGHTS = (SELECT  MAX(TOTAL_NIGHTS)
                                        FROM VILLA_NIGHT_SUM
                                        )
                  )
;

DROP VIEW VILLA_NIGHT_SUM;