CREATE VIEW VILLA_RENT_OWNER AS
SELECT VILLA_OWNER_ID OWNER, COUNT(*) VILLA_RENT_OWNER_COUNT
FROM WEB_VILLA
WHERE VILLA_ID NOT IN(SELECT RENT_VILLA_ID 
                        FROM WEB_RENT
                        WHERE (RENT_START_DATE < '15-AUG-2014'
                        OR RENT_START_DATE = '15-AUG-2014')
                        AND (RENT_END_DATE > '15-AUG-2014'
                        OR RENT_END_DATE = '15-AUG-2014')
                        )
GROUP BY VILLA_OWNER_ID
;
CREATE VIEW VILLA_RENT AS
SELECT VILLA_OWNER_ID, COUNT(*) VILLA_RENT_COUNT
FROM WEB_VILLA
GROUP BY VILLA_OWNER_ID
;
/*
SELECT *
FROM VILLA_RENT_OWNER
;

SELECT *
FROM VILLA_RENT
;
*/
SELECT USER_FIRST_NAME, USER_LAST_NAME, VACANCY_RATIO
FROM WEB_USER,(SELECT VILLA_OWNER_ID,VILLA_RENT_OWNER_COUNT/VILLA_RENT_COUNT VACANCY_RATIO
                FROM VILLA_RENT, VILLA_RENT_OWNER
                WHERE VILLA_OWNER_ID = OWNER) VILLA_OWNER
WHERE VILLA_OWNER_ID = USER_ID
;

DROP VIEW VILLA_RENT_OWNER;
DROP VIEW VILLA_RENT;